### PR TITLE
DevExtreme translations for 'pt' and 'es' locale for version 17.1.5

### PR DESCRIPTION
**Pull request by pedrofurtado**
@BingoRUS DevExtreme translations for 'pt' and 'es' locale for version 17.1.5

### CODE REVIEW

**Comment by pedrofurtado** [comment]
@BingoRUS Any news about this pull request?

**Comment by pedrofurtado** [comment]
@BingoRUS Any news about this pull request?

**Comment by BingoRUS** [comment]
@pedrofurtado Thank you for the pull request and sorry for being late with my answer. Our bower repositories contain generated scripts. So I'm not sure I could merge your changes. However, [the DevExtreme source code](https://github.com/DevExpress/DevExtreme) is here on GitHub as well. Could you please create a pull request there?

You will need to make just tiny changes in your files: the localization sources are just JSON files without helper functions and license headers. Please take a look here: https://github.com/DevExpress/DevExtreme/tree/17_2/js/localization/messages

Also, I would kindly ask you to add some more localization constants according to the 17.2 version changes.

**Comment by pedrofurtado** [comment]
@BingoRUS Thanks for feedback! I've created the pull request in the another repository.

**Comment by BingoRUS** [comment]
I see your [pull request](https://github.com/DevExpress/DevExtreme/pull/2323) in the DevExtreme repository. Thanks! After it's merged, you will see new localization files in the next Bower and npm packages. I will close this PR now.

**Pull request closed without merging**
